= FpDebug

link:https://www.gnu.org/licenses/gpl-2.0.html[image:https://img.shields.io/badge/license-GPL2-blue.svg[GNU General Public License, version 2]]

FpDebug  is a heavyweight Valgrind tool for detecting floating-point accuracy problems.

The tool uses MPFR for its side-by-side computation in higher precision.
Because MPFR is run with the tool on top of Valgrind,
it has only access to the partial C library provided by Valgrind.
Thus, a patch for MPFR is provided that adjusts it to run on top of Valgrind.
As GMP is used by MFPR, a patch for GMP is also provided.

== Origin

This project was started during my Bachelor's thesis (winter 2010/11).
The results have been published in:

link:http://dl.acm.org/citation.cfm?id=2254118[A Dynamic Program Analysis to find Floating-Point Accuracy Problems]
link:https://www.fbenz.net/static/pldi12_benz.pdf[[PDF]] +
link:https://www.fbenz.net/[Florian Benz],
link:https://www.bio.informatik.uni-mainz.de/andreas-hildebrandt/[Andreas Hildebrandt], and
link:http://compilers.cs.uni-saarland.de/people/hack/[Sebastian Hack] +
PLDI '12: Proceedings of the 2012 ACM SIGPLAN Conference on Programming Language Design and Implementation

== Quick start

The `docker` folder contains Dockfiles for several systems
that can be used to build and play around.
During the build a small example program is also built and
analyzed to check that everything works.

[source,bash]
.Build and run Docker image
----
sudo docker build -t fpdebug .
sudo docker run -it fpdebug /bin/bash
----

== Build from source

NOTE: Only 64bit systems are supported.

The following installation instructions are for Ubuntu 16.10 (64bit).
The instructions should be similar for most other Linux systems.

[source,bash]
.Install build dependencies
----
# Git is only needed to check out the sources
sudo apt-get install git
# m4 is a dependency of GMP
sudo apt-get install m4
# libc6-dbg is required for Valgrind (otherwise it fails at runtime)
sudo apt-get install libc6-dbg
----

[source,bash]
.Get the sources
----
git clone git@github.com:fbenz/FpDebug.git
----

[source,bash]
.Install patched GMP 5.0.1
----
./install_gmp.sh
----

[source,bash]
.Install patched MPFR 3.0.0
----
./install_mpfr.sh
----

[source,bash]
.Install Valgrind with FpDebug
----
./install_valgrind.sh
----

== Running FpDebug

[source,bash]
.Build an example
----
cd valgrind/fpdebug/examples
gcc test_1.c -O0 -g -o test_1.out
(or $ gcc test_1.c -O0 -g -mfpmath=387 -o test_1.out )
----

[source,bash]
.Run FpDebug
----
./valgrind/install/bin/valgrind --tool=fpdebug valgrind/fpdebug/examples/test_1.out
----

[source,bash]
.FpDebug output
----
==15351== FpDebug-0.2, Floating-point arithmetic debugger
==15351== Copyright (C) 2010-2017 by Florian Benz.
==15351== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==15351== Command: valgrind/fpdebug/examples/test_1.out
==15351== 
==15351== precision=120
==15351== mean-error=yes
==15351== ignore-libraries=no
==15351== ignore-accurate=yes
==15351== sim-original=no
==15351== analyze-all=yes
==15351== bad-cancellations=yes
==15351== ignore-end=no
Test program: machine epsilon, client request
Sum: 1.0000000e+00
Running on valgrind
==15351== (float) sum PRINT ERROR OF: 0xFFEFFF60C
==15351== (float) sum ORIGINAL:          1.00000000000000 * 10^0, 1/120 bit
==15351== (float) sum SHADOW VALUE:      1.00000025000000 * 10^0, 49/120 bit
==15351== (float) sum ABSOLUTE ERROR:    2.50000002921524 * 10^-7, 27/120 bit
==15351== (float) sum RELATIVE ERROR:    2.49999940421539 * 10^-7, 120/120 bit
==15351== (float) sum CANCELED BITS:     0
==15351== (float) sum Last operation: 0x108A19: main (test_1.c:14)
==15351== (float) sum Operation count (max path): 5
==15351== DUMP GRAPH (test_1_sum.vcg): successful
==15351== 
==15351== DUMP GRAPH (valgrind/fpdebug/examples/test_1.out_1_0.vcg): successful
==15351== SHADOW VALUES (valgrind/fpdebug/examples/test_1.out_shadow_values_relative_error_8): successful
==15351== SHADOW VALUES (valgrind/fpdebug/examples/test_1.out_shadow_values_canceled_8): successful
==15351== SHADOW VALUES (valgrind/fpdebug/examples/test_1.out_shadow_values_special_8): successful
==15351== MEAN ERRORS (valgrind/fpdebug/examples/test_1.out_mean_errors_addr_8): successful
==15351== MEAN ERRORS (valgrind/fpdebug/examples/test_1.out_mean_errors_canceled_8): successful
==15351== MEAN ERRORS (valgrind/fpdebug/examples/test_1.out_mean_errors_intro_8): successful
==15351== DEBUG - Client exited with code: 0
--15351-- DEBUG - SBs: 1,888, executed: 31,743, instr: 66,328
--15351-- DEBUG - ShadowValues (frees/mallocs): 0/14, diff: 14
--15351-- DEBUG - Floating-point operations: 5
--15351-- DEBUG - Max temps: 396
--15351-- OPTIMIZATION - GET:   total 4,456, ignored: 181
--15351-- OPTIMIZATION - STORE: total 1,881, ignored: 0
--15351-- OPTIMIZATION - PUT:   total 16,367, ignored: 36
--15351-- OPTIMIZATION - LOAD:  total 2,681, ignored: 0
----

=== License

FpDebug is Open Source software released under the link:https://www.gnu.org/licenses/gpl-2.0.html[GNU General Public License, version 2].

