= FpDebug

FpDebug  is a heavyweight Valgrind tool for detecting floating-point accuracy problems.

The tool uses MPFR for its side-by-side computation in higher precision.
Because MPFR is run with the tool on top of Valgrind,
it has only access to the partial C library provided by Valgrind.
Thus, a patch for MPFR is provided that adjusts it to run on top of Valgrind.
As GMP is used by MFPR, a patch for GMP is also provided.

NOTE: The tool was only tested on 64bit systems.

== Build from source

The following installation instructions are for Ubuntu 16.10 (64bit).
The instructions should be similar for most other Linux systems.

[source,bash]
.Install build dependencies
----
# Git is only needed to check out the sources
sudo apt-get install git
# m4 is a dependency of GMP
sudo apt-get install m4
# libc6-dbg is required for Valgrind (otherwise it fails at runtime)
sudo apt-get install libc6-dbg
----

[source,bash]
.Get the sources
----
git clone git@github.com:fbenz/FpDebug.git
----

[source,bash]
.Install patched GMP 5.0.1
----
./install_gmp.sh
----

[source,bash]
.Install patched MPFR 3.0.0
----
./install_mpfr.sh
----

[source,bash]
.Install Valgrind with FpDebug
----
./install_valgrind.sh
----

== Running FpDebug

[source,bash]
.Build an example
----
cd valgrind/fpdebug/examples
gcc test_1.c -O0 -g -o test_1.out
(or $ gcc test_1.c -O0 -g -mfpmath=387 -o test_1.out )
----

[source,bash]
.Run FpDebug
----
./valgrind/install/bin/valgrind --tool=fpdebug valgrind/fpdebug/examples/test_1.out
----

[source,bash]
.FpDebug output
----
==19945== FpDebug-0.2, Floating-point arithmetic debugger
==19945== Copyright (C) 2010-2017 by Florian Benz.
==19945== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==19945== Command: valgrind/fpdebug/examples/test_1.out
==19945==
==19945== precision=120
==19945== mean-error=yes
==19945== ignore-libraries=no
==19945== ignore-accurate=yes
==19945== sim-original=no
==19945== analyze-all=yes
==19945== bad-cancellations=yes
==19945== ignore-end=no
Test program: machine epsilon, client request
Sum: 1.0000000e+00
Running on valgrind
==19945== (float) sum PRINT ERROR OF: 0xFFEFFF5AC
==19945== (float) sum ORIGINAL:          1.00000000000000 * 10^0, 1/120 bit
==19945== (float) sum SHADOW VALUE:      1.00000025000000 * 10^0, 49/120 bit
==19945== (float) sum ABSOLUTE ERROR:    2.50000002921524 * 10^-7, 27/120 bit
==19945== (float) sum RELATIVE ERROR:    2.49999940421539 * 10^-7, 120/120 bit
==19945== (float) sum CANCELED BITS:     0
==19945== (float) sum Last operation: (null)
==19945== (float) sum Operation count (max path): 5
==19945== DUMP GRAPH (test_1_sum.vcg): successful
==19945==
==19945== DUMP GRAPH (valgrind/fpdebug/examples/test_1.out_1_0.vcg): successful
==19945== SHADOW VALUES (valgrind/fpdebug/examples/test_1.out_shadow_values_relative_error_1): successful
==19945== SHADOW VALUES (valgrind/fpdebug/examples/test_1.out_shadow_values_canceled_1): successful
==19945== SHADOW VALUES (valgrind/fpdebug/examples/test_1.out_shadow_values_special_1): successful
==19945== MEAN ERRORS (valgrind/fpdebug/examples/test_1.out_mean_errors_addr_1): successful
==19945== MEAN ERRORS (valgrind/fpdebug/examples/test_1.out_mean_errors_canceled_1): successful
==19945== MEAN ERRORS (valgrind/fpdebug/examples/test_1.out_mean_errors_intro_1): successful
==19945== DEBUG - Client exited with code: 0
--19945-- DEBUG - SBs: 1,888, executed: 31,864, instr: 66,328
--19945-- DEBUG - ShadowValues (frees/mallocs): 0/14, diff: 14
--19945-- DEBUG - Floating-point operations: 5
--19945-- DEBUG - Max temps: 396
--19945-- OPTIMIZATION - GET:   total 4,456, ignored: 181
--19945-- OPTIMIZATION - STORE: total 1,881, ignored: 0
--19945-- OPTIMIZATION - PUT:   total 16,367, ignored: 36
--19945-- OPTIMIZATION - LOAD:  total 2,681, ignored: 0
----
